### ISSUE TITLE
How to set server ping timeout?

### ISSUE THREAD

**Issue by chongivan** [pusher/pusher-websocket-java#59]
Say user A and user B are subscribed to a presenceChannel.

A disables his wifi.
B's **presenceChannel.getUsers().size()** still shows 2, even after one or two minutes.

B will receive a **userUnsubscribed** event only after **7 mins**.

The below
```java
options.setActivityTimeout(long ms);
options.setPongTimeout(long ms);
```
Sets client timeouts, so they dont help.

Is there a way to shorten the **server** ping timeputs, so that B receives a quick **userUnsubscribed** event?

**Comment by mdpye** [comment]
There is not a way for a client to set the server-side timeout, no. We are considering reducing it across the board in order to let other clients know more quickly about disconnections.

**Comment by chongivan** [comment]
Noted with thanks. 

Btw, when you do reduce it, where could I be notified?

**Comment by leggetter** [comment]
@chongivan - @mdpye reduced the time before the Pusher servers send a ping from 300 to 200 seconds yesterday morning.

**Comment by mdpye** [comment]
I intend to reduce it further, to 140s, based on some testing I've been doing. I will likely reduce the time we wait for the response to ping from 60 to 30s as well. This should yield a *maximum* wait of 170s before a dead connection is detected.

**Comment by chongivan** [comment]
@mdpye @leggetter thank you, your quick responses are appreciated =)
That still equates to 2.83333mins, as the *whole duration* is required to determine a disconnected client.
Not really real time, unless we implement the ping pong ourselves.

**Comment by mdpye** [comment]
It's not ideal. It's a frustrating fact that in some unclean disconnection scenarios, TCP connection failure cannot be distinguished from an idle connection.

I'd like to further improve on the timing we offer, but it is not straight-forward. Some confounding factors include:
 - Volume: With a huge number of mostly idle (awaiting broadcast from the server) clients, reductions in the server ping timeout yield very quickly escalating levels of traffic dedicated to just pings.
 - Mobile radios / metered traffic: Every ping from the server means firing up the radio on a mobile client, and we don't wish to keep the radio awake when there's no useful traffic to be exchanged.

Unfortunately, to cover the detection of silent, unclean disconnections in anything which could be labelled "real time" would mean passing *constant* traffic between client and server. I encourage you to investigate with scepticism anyone claiming otherwise (or be aware of how much traffic they're generating if they take this path).

Of course, clean disconnections (almost anything where the client is not physically disconnected without warning) and some unclean disconnections are noticed at the TCP layer and processed immediately.

Also, a small nitpick correction to your statement. The "whole duration" is the period between the client last sending data to the server and the disconnection being confirmed. The time to notice a disconnection is in the range 30 to 170 seconds depending on when the actual disconnection takes place with respect to the last client -> server traffic. I realise this is not of much solace.

You are free to tune the client side timeouts, these will not help user A discover than user B has become disconnected, but at least enable you to get user B back online (providing their connection failure was transient) as quickly as possible, so that the notifying user A becomes less important.

**Comment by chongivan** [comment]
@mdpye, valid points indeed.
Will work with these practices, thank you =)
