### ISSUE TITLE
Pusher Channel already subcscribed

### ISSUE THREAD

**Issue by macin11** [pusher/pusher-websocket-java#66]
Is there any method to check if pusher is already subscribed.Because in pusher jar ver 0.0.3 an exception was thrown whenever a pusher is resubscribed.And also to clarify ,when pusher is reconnected again or it just maintain its previous state without resubscribing?

**Comment by ruckus** [comment]
I came here to get an answer to this exact question. Basically, whats the best practice for integrating Pusher into an Android application where if you subscribe in `Activity#onCreate` and you come back to that activity this exception is thrown. I've (temporarily?) resolved this by catching that exception - but I feel like there must be a better way.

I saw #10 and that ticket doesnt have any answers. If there was a way to check first that would be useful:

```java
if(!pusher.hasSubscribed("channel-name")) {
   pusher.subscribe(...);
}
```

**Comment by leggetter** [comment]
The PR https://github.com/pusher/pusher-websocket-java/pull/12 addresses this but just needed to be updated to use the correct naming conventions. If anybody would like to take that PR and change the methods to be named `isSubscribedTo` then I'll merge the PR.

If nobody has the time to do that right now then I'll do it tonight. I'll probably also look at merging in https://github.com/pusher/pusher-websocket-java/pull/57 since we really should be using Gradle.

**Comment by leggetter** [comment]
Please see https://github.com/pusher/pusher-websocket-java/issues/67#issuecomment-129912947

**Comment by jpatel531** [comment]
Closing for now as #74 has been merged
